name: ssnr_sim
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pip
  - pyqt
  - pyqtgraph
  - python=3.9
  - scikit-learn
  - scipy
  - pip:
    - MyoSuite==2.8.0
    - dm_control==1.0.16
    - mujoco==3.1.2
    - stable_baselines3[extra]==2.6.0
    - tensorboard==2.20.0
    - shimmy[dm_control]
