name: ssnr_sim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - scipy
  - pip
  - scikit-learn
  - pyqt
  - pyqtgraph
  - pip:
    - mujoco
    - dm_control
    - "shimmy[dm_control]"
    - "stable-baselines3[extra]"
    - "tensorboard"
    - myosuite
    - loop_rate_limiters

